export const GET_COMMENT_CLICKED = "GET_COMMENT_CLICKED";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_FAILED = "GET_COMMENT_FAILED";

export const CLEAN_COMMENTS = "CLEAN_COMMENTS";

export const GET_STORY_START = "GET_STORY_START";
export const GET_STORY_SUCCESS = "GET_STORY_SUCCESS";
export const GET_STORY_FAILED = "GET_STORY_FAILED";

export const GET_TOP_STORIES_START = "GET_TOP_STORIES_START";
export const GET_TOP_STORIES_SUCCESS = "GET_TOP_STORIES_SUCCESS";
export const GET_TOP_STORIES_FAILED = "GET_TOP_STORIES_FAILED";

export const GET_MAX_ITEM_START = "GET_MAX_ITEM_START";
export const GET_MAX_ITEM_SUCCESS = "GET_MAX_ITEM_SUCCESS";
export const GET_MAX_ITEM_FAILED = "GET_MAX_ITEM_FAILED";

export const GET_ALL_STORIES_START = "GET_ALL_STORIES_START";
export const GET_ALL_STORIES_SUCCESS = "GET_ALL_STORIES_SUCCESS";
export const GET_ALL_STORIES_FAILED = "GET_ALL_STORIES_FAILED";

export const SHOW_LOADING = "SHOW_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";

export const START_LOGIN = "START_LOGIN";
export const LOGIN_CLICKED = "LOGIN_CLICKED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_FAILED_VALIDATION_EMAIL = "LOGIN_FAILED_VALIDATION_EMAIL";

export const FORGET_PASSWORD_CLICKED = "FORGET_PASSWORD_CLICKED";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAILED = "FORGET_PASSWORD_FAILED";

export const SET_REDIRECT_PATH = "SET_REDIRECT_PATH";

export const CREATE_PROFILE_CLICKED = "CREATE_PROFILE_CLICKED";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_FAILED = "CREATE_PROFILE_FAILED";
export const SHOULD_VALIDATE_EMAIL = "SHOULD_VALIDATE_EMAIL";

export const UPDATE_PROFILE_CLICKED = "UPDATE_PROFILE_CLICKED";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

export const GET_ALL_USERS_START = "GET_ALL_USERS_START";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILED = "GET_ALL_USERS_FAILED";

export const GET_THEME = "GET_THEME";
export const UPDATE_THEME = "UPDATE_THEME";
